= План выступления на защите ВКР
Время на выступление 15--20 минут.

== 1. Титульный слайд
Внедрение системы автоматизации развертывания, масштабирования и управления контейнеризованными приложениями в компании ЗАО "Эвалар"

== 2. Содержание

== 3. Цель и задачи, актуальность
Целью работы является внедрение системы автоматизации развертывания масштабирования и управления контейнеризованными приложениями, и использование этой системы для развертывания стендов разработчиков, оптимизации работы с ними, а также впоследствии для совершенствования производственной среды. 

Для достижения этой цели выделены следующие задачи:
    • поиск и выбор подходящей системы;
    • сравнение и выбор дистрибутива системы (при наличии таковых);
    • тестовое развертывание системы;
    • развертывание стенда разработчиков для одного из сайтов с применением рассматриваемой системы;
    • анализ успешности развертывания и применимости для использования в производственной среде;
    • развертывание производственной среды одного из веб-сайтов с применением рассматриваемой системы;
    • последовательный перенос остальных производственных сред в кластер.

Актуальность данной работы заключается в необходимости повышения отказоустойчивости веб-сайтов компании ЗАО «Эвалар», увеличения портативности программного обеспечения во избежание зависимости от какого-либо конкретного поставщика облачных услуг, а также для автоматизации внутренних рабочих процессов.

== 4. Теоритическая часть
== 5. DEVOPS
Для начала рассмотрим некоторые базовые понятия и кратко опишем методологию DevOps.

DevOps — (от англ. Development и Operations) это набор практик и инструментов, подход к работе, который позволяет компании наладить эффективное взаимодействие сотрудников, занимающихся разработкой ПО, с другими IT-специалистами.

С точки зрения инструментов суть этой методологии заключается в автоматизации и интегрировании рабочих процессов между командами разработки и другими командами IT.

Относительно же взаимодействия между командами, они более не являются «изолированными».

Цикл DevOps (на картинке).
8 этапов.

== 6. Барьеры внедрения DevOps
В ходе проведения исследования был изучен публикуемый раз в несколько лет отчет от компании Puppet Labs -- State of DevOps.

Согласно данному отчету, можно выделить несколько барьеров на пути внедрения DevOps. (на слайде).

Также можно разделить на уровни по степени внедрения этой методологии: низкий, средний, высокий.

== 7. Linux контейнеры
Контейнеризация -- один из видов легкой виртуализации. В данном случае речь пойдет о контейнеризации операционных систем на базе ядра Linux, хотя есть и другие виды контейнеризации. Стоит упомянуть, что в других ОС также есть схожие технологии. Напмриер, в FreeBSD -- Jails.

Существует множество сред выполнения контейнеров для разных сценариев применения и с разной степенью защищенности.

Среди низкоуровневых можно выделить: LXC, runc; уровнем выше: containerd, CRI-O; наиболее распространенные высокоуровневые инстурменты: Docker, Podman, LXD.

== 8. Области видимости
Двумя основополагающими технологиями, реализующими контейнеризацию в ядре Linux являются области видимости и контрольные группы.

Области видимости -- абстракции над глобальными ресурсами, разделяющие и изолирующие их.

Доступ к ресурсам внутри изолированных пространств имен есть у процессов-участников этих пространств, но не у других процессов.

== 9. Контрольные группы
cgroups (от англ. control groups, контрольные группы) — механизм ядра Linux для иерархической организации процессов и контролируемого, конфигурируемого распределения системных ресурсов в этой иерархии. Контрольные группы образуют древовидную структуру, и каждый процесс в системе одновременно может принадлежать только к одной контрольной группе. Все потоки и дочерние процессы принадлежат той же контрольной группе, что и родительский процесс. При этом, возможно выполнение миграции процесса в другую контрольную группу.

== 10. Управление конфигурацией
Специализированные инструменты автоматизации управления конфигурацией инфраструктуры позволяют описывать желаемое состояние инфраструктуры в определенном формате, более унифицированном и контролируемом. 

Это позволяет реализовывать подход IaC, при котором конфигурация хранится в виде кода в системе управления версиями, такой как git.

== 11. Практическая часть

== 12. До вмешательства
* виртуальный ЦОД на базе РЕКОНН

* ручное развертывание вм с клонировеним
* разрозненность инфраструктуры
* стенды разворачиваются через Jenkins CD

== 13. Проблемы
В ходе исследования предмета данной работы было установлено, что компания ЗАО "Эвалар" находится на минимальном уровне принятия методологии DevOps.

На слайде

== 14. Орекстрация
Для увеличения портативности, снижения нагрузки на рабочий персонал, и обеспечения возможностей автоматического поддержания здоровья рабочей нагрузки, наряду с другими преимуществами, было решено применить оркестрацию.

Выбор был между Kubernetes, Nomad и Docker Swarm mode. Согласно определенным критериям выбран стандартный дистрибутив Kubernetes от Google.

== 15. Управление конфигурацией
Среди рассмартиваемых систем: Ansible, Puppet, Chef по определенным критериям была выбрана Ansible.

== 16. Автоматическое развертывание
Среди Pulumi и Terraform был выбран первый инструмент, так как является более гибким за счет использования языков программирования вместо специализированных язков конфигурации.

== 17. План
На слайд

== 18. Тренировочный проект
В качестве тренировочного проекта был выбран сайт corp.evalar.ru, так как состоит из наименьшего количества компонентов.

== 19. Архитектура кластера
На слайде

== 20. Портирование | Образы
Для портирования созданы несколько контейнерфайлов. Причем, некоторые в формате обычных сценариев командной оболочки. Возможно это благодаря использованию инструмента Buildah, и такой подход очень гибкий.

== 21. Портирование | Helm-чарт
Для непосредственного развертывания веб-сайта в кластере Kubernetes применяется пакетный менеджер Helm. Количество кода оказалось большим, 546 строк.

== 22. Портирование | Пример манифеста
Это для роли, ограничивающей взаимодействие разработчиков с кластером.

== 23. Проектная документация | Установка
Конкретные инструкции по развертыванию рассмотрены не будут, но на слайдах несколько примеров из проектной документации.

== 24. Проектная документация | Установленный чарт
Установленный чарт состоит из нескольких компонентов, примеры которых также есть в проектной документации.

== 25,26. Подключение к стендам | Проброс портов
Для к стендам внутри кластера разработчики сначала выполняют проброс портов на локальной машине, а затем непосредственно подключение по протоколу SSH.

== 27. Подключение к стендам | HTTP
Для проверки правильности отображения веб-страниц можно получить доступ к любому стенду внутри сети компании по доменному имени каждого разработчика.

== 28. Дальнейшее развитие
На данный момент релизовано 5 этапов из 12. Остальные запланированы, но сроки могут меняться в зависимости от обстоятельств.

== 29. Экономическая часть
== 30. Расчет затрат на аренду
Так как используется виртуальный ЦОД, то подсчитать расходы можно в спецаильном калькуляторе на сайте поставщика.
С текущими требованиями получается около 16 тыс./мес.

== 31. Заключение
