= План выступления на защите ВКР
Время на выступление 7--10 минут (с вопросами от комиссии 15--20).

== 1. Титульный слайд
Внедрение системы автоматизации развертывания, масштабирования и управления контейнеризованными приложениями в компании ЗАО "Эвалар"

== 2. Содержание

== 3. Цель и задачи, актуальность
.Цель
****
Внедрение системы автоматизации развертывания, масштабирования и управления контейнеризованными приложениями: 

* Использование ее для стендов разработчиков
* Оптимизация работы с ними
* Совершенствование производственной среды впоследствии
****

.Задачи
****
Для достижения этой цели выделены следующие задачи:

* Поиск и выбор подходящей системы
* Сравнение и выбор дистрибутива системы (при наличии таковых)
* Тестовое развертывание системы
* Развертывание стенда разработчиков для одного из сайтов с применением рассматриваемой системы
* Анализ успешности развертывания и применимости для использования в производственной среде
* Развертывание производственной среды одного из веб-сайтов с применением рассматриваемой системы
* Последовательный перенос остальных производственных сред в кластер
****

.Актуальность
****
* Необходимость повышения отказоустойчивости веб-сайтов
* Исключение возможности зависимости от конкретного поставщика облачных услуг
* Автоматизация внутренних процессов
****

== 4. Теоритическая часть
== 5. DEVOPS
Для начала рассмотрим некоторые базовые понятия и кратко опишем методологию DevOps.

DevOps — (от англ. Development и Operations) это набор практик и инструментов, позволяющий наладить эффективное взаимодействие разработчиков ПО с другими IT-специалистами.

С точки зрения инструментов суть этой методологии заключается в автоматизации и интегрировании рабочих процессов между командами разработки и другими командами IT.

Относительно же взаимодействия между командами, они более не являются «изолированными».

Цикл DevOps (на картинке).
8 этапов.

== 6. Барьеры внедрения DevOps
В ходе проведения исследования был изучен публикуемый раз в несколько лет отчет от компании Puppet Labs -- State of DevOps.

Согласно данному отчету, можно выделить несколько барьеров на пути внедрения DevOps. (на слайде).

Также можно разделить на уровни по степени внедрения этой методологии: низкий, средний, высокий.

== 7. Linux контейнеры
Контейнеризация -- один из видов легкой виртуализации. 

В данном случае речь пойдет о контейнеризации операционных систем на базе ядра Linux, хотя есть и другие виды контейнеризации.

В других ОС также есть схожие технологии. Напмриер, в FreeBSD -- Jails.

.Существует множество сред выполнения контейнеров разных уровней
****
Распространенные низкоуровневые:

* LXC
* runc

Уровнем выше:

* containerd
* CRI-O

Высокоуровневые:

* Docker
* Podman
****

== 8. Области видимости
Двумя основополагающими технологиями, реализующими контейнеризацию в ядре Linux являются области видимости и контрольные группы.

Области видимости -- абстракции над глобальными ресурсами, разделяющие и изолирующие их.

Доступ к ресурсам внутри изолированных пространств имен есть у процессов-участников этих пространств, но не у других процессов.

== 9. Контрольные группы
Контрольные группы — механизм ядра Linux для иерархической организации процессов и контролируемого распределения системных ресурсов в этой иерархии. 

Каждый процесс в системе одновременно может принадлежать только к одной контрольной группе, с возможностью миграции.

== 10. Практическая часть

== 11. До вмешательства
* Виртуальный ЦОД на базе РЕКОНН
* Ручное развертывание вм с клонировеним
* Разрозненность инфраструктуры
* Стенды разворачиваются через Jenkins CD

== 12. Проблемы
ЗАО "Эвалар" находится на минимальном уровне принятия методологии DevOps.

На слайде

== 13. Орекстрация
.Для
****
* Увеличения портативности
* Снижения нагрузки на персонал
* Автоматического поддержания здоровья рабочей нагрузки
****

Выбор был между Kubernetes, Nomad и Docker Swarm mode. По критериям в пояснительной записке выбран стандартный Kubernetes от Google.

== 14. Управление конфигурацией
Среди рассмартиваемых систем: Ansible, Puppet, Chef по определенным критериям была выбрана Ansible.

== 15. Автоматическое развертывание
Среди Pulumi и Terraform был выбран первый инструмент, так как является более гибким за счет использования языков программирования вместо специализированных язков конфигурации.

== 16. План
На слайде

== 17. Тренировочный проект
В качестве тренировочного проекта был выбран сайт corp.evalar.ru, так как состоит из наименьшего количества компонентов.

== 18. Архитектура кластера
На слайде

* Имеется один хост панели управления
* Доступ от воркеров через балансировщик с доменным именем,
так что возможно добавить больше узлов
* Доступ от пользователей в сети, где кластер, благодаря публикации
сервисов через балансировщик MetalLB
* Вне кластера имеется хранилище данных и реестр образов контейнеров

== 19. Портирование | Образы
Для портирования созданы несколько контейнерфайлов. Причем, некоторые в формате обычных сценариев командной оболочки. Возможно это благодаря использованию инструмента Buildah, и такой подход очень гибкий.

== 20. Портирование | Helm-чарт
Для непосредственного развертывания веб-сайта в кластере Kubernetes применяется пакетный менеджер Helm. Количество кода оказалось большим, 546 строк. Но это не является недостатком, потому что изменения будут редкими.

== 21. Портирование | Пример манифеста
Это для роли, ограничивающей взаимодействие разработчиков с кластером.

== 22. Проектная документация | Установка
Конкретные инструкции по развертыванию рассмотрены не будут, но на слайдах несколько примеров из проектной документации.

== 23. Проектная документация | Установленный чарт
Установленный чарт состоит из нескольких компонентов, примеры которых также есть в проектной документации.

== 24,25. Подключение к стендам | Проброс портов
Для к стендам внутри кластера разработчики сначала выполняют проброс портов на локальной машине, а затем непосредственно подключение по протоколу SSH.

== 26. Подключение к стендам | HTTP
Для проверки правильности отображения веб-страниц можно получить доступ к любому стенду внутри сети компании по доменному имени каждого разработчика.

== 27. Дальнейшее развитие
На данный момент релизовано 5 этапов из 12. Остальные запланированы, но сроки могут меняться в зависимости от обстоятельств. 

ISO 8601-2.

== 28. Экономическая часть
== 29. Расчет затрат на аренду
Так как используется виртуальный ЦОД, то подсчитать расходы можно в спецаильном калькуляторе на сайте поставщика.

С текущими требованиями получается около 16 тыс./мес.

== 30. Заключение
Таким образом, в ходе выполнения работы были достигнуты поставленные цели и задачи, что стало толчком к дальнейшей модернизации инфраструктуры компании, которая будет осуществляться согласно намеченному плану.
